spring.application.name=department-service
server.port=8082

# Mysql database host (Dung host.docker.internal de noi tu container ra MySQL tren may that)
spring.datasource.url=${DB_URL:jdbc:mysql://host.docker.internal:3306/microservice?createDatabaseIfNotExist=true&characterEncoding=UTF-8&serverTimeZone=UTC}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root}

# Khai bao truc tiep Dialect va DDL de Hibernate khong bao loi khi khoi dong
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true