apiVersion: apps/v1
kind: Deployment
metadata:
  name: department-service
  labels:
    app: department-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: department-service
  template:
    metadata:
      labels:
        app: department-service
    spec:
      containers:
      - name: department-service
        image: department-service:${IMAGE_TAG}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8082
        envFrom:
        - secretRef:
            name: department-service-secret